version: "3.8"

services:
  langflow:
    image: langflowai/langflow:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      LANGFLOW_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      LANGFLOW_CONFIG_DIR: /app/langflow
    volumes:
      - langflow-data:/app/langflow
    networks:
      - default

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  langflow-postgres:
  langflow-data:

networks:
  default:
    external:
      name: dokploy-network